# Generated by Django 3.1.5 on 2021-12-08 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('inquiry', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2021, 12, 8, 10, 45, 45, 958455, tzinfo=utc))),
            ],
        ),
    ]
